application: invert-demo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: assets/images/favicon.ico
  upload: assets/images/favicon.ico

- url: /assets
  static_dir: assets

- url: .*
  script: myapp.app